### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by dwhall** [tpschmit/hierarchical-state-machines#1]
Sorry, this is not an issue (you may delete this); it's just the only way I could find to contact you.  I wanted to let you know I've made a QP clone in Python3 using asyncio for event timers and run-to-completion: [https://github.com/dwhall/pq](https://github.com/dwhall/pq)

I also have a [project](https://github.com/dwhall/HeyMac/blob/master/heymac/mac_tdma_ahsm.py) that is using pq on a Raspberry Pi and I'm getting pretty good real-time control.  I use the pq TimerEvent to get within 10ms of the target time and then the builtin time.sleep() to get within 1ms and often 0.1ms of the target time.

**Comment by tpschmit** [comment]
Dean,

Thanks for sending the link. Keep up the good work! I cloned it
and successfully ran all the examples. Haven't looked the Pi project yet.

Best,
Tom

**Comment by dwhall** [comment]
I also just found this project: https://github.com/aleph2c/miros
that has good docs: https://aleph2c.github.io/miros/index.html
It makes me wonder if the three of us are the entire set of humans coding AHSMs in Python.
